package com.igu.pepperprofesor.question;

import android.os.Build;

import androidx.annotation.RequiresApi;

import com.igu.pepperprofesor.MainActivity;
import com.igu.pepperprofesor.R;
import com.igu.pepperprofesor.Subject;
import com.igu.pepperprofesor.Utilities;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static com.igu.pepperprofesor.Subject.CASTELLANO;
import static com.igu.pepperprofesor.Subject.MATEMATICAS;
import static com.igu.pepperprofesor.Subject.SOCIALES;

public class QuestionUtils {
    private static final List<Question> questions;

    static {
        questions = Arrays.asList(
                new OptionQuestion(SOCIALES, 1, "¿Alrededor de qué tipo de astro orbitan los satélites?",
                        Arrays.asList(new Option('a', "Planetas"),
                                new Option('b', "Estrellas"),
                                new Option('c', "Agujeros negros"))),
                new OptionQuestion(SOCIALES, 2, "¿Qué forma tiene la galaxia en la que se encuentra la Tierra?",
                        Arrays.asList(new Option('a', "Quásar"),
                                new Option('b', "Elíptica"),
                                new Option('c', "Espiral"))),
                new OptionQuestion(SOCIALES, 3, "¿Qué tipo de estrella es el Sol?",
                        Arrays.asList(new Option('a', "Enana"),
                                new Option('b', "Mediana"),
                                new Option('c', "Grande"))),
                new Question(SOCIALES, 4, "¿En qué planeta del sistema solar a parte de la Tierra se encuentra el Monte Olimpo?"),
                new OptionQuestion(SOCIALES, 5, "¿En qué año llegaron los humanos a la Luna?",
                        Arrays.asList(new Option('a', "1973"),
                                new Option('b', "1969"),
                                new Option('c', "1968"))),
                new Question(SOCIALES, 6, "¿Cómo se llaman las circunferencias imaginarias paralelas al Ecuador?"),
                new Question(SOCIALES, 7, "¿Cómo se llaman las circunferencias imaginarias que pasan por los Polos Norte y Sur?"),
                new OptionQuestion(SOCIALES, 8, "¿Entre qué paises están los Pirineos?",
                        Arrays.asList(new Option('a', "España y Francia"),
                                new Option('b', "Portugal y España"),
                                new Option('c', "Italia y Francia"))),
                new OptionQuestion(SOCIALES, 9, "¿Cuál es el río más largo de España?",
                        Arrays.asList(new Option('a', "Duero"),
                                new Option('b', "Guadalquivir"),
                                new Option('c', "Tajo"))),
                new OptionQuestion(SOCIALES, 10, "¿Cuál es la montaña más alta de España?",
                        Arrays.asList(new Option('a', "Mulhacén"),
                                new Option('b', "Teide"),
                                new Option('c', "Aneto"))),
                new OptionQuestion(SOCIALES, 11, "¿Con qué océano está en contacto España?",
                        Arrays.asList(new Option('a', "Atlántico"),
                                new Option('b', "Pacífico"),
                                new Option('c', "Índico"))),
                new Question(SOCIALES, 12, "¿A qué continente pertenece Australia?"),
                new Question(SOCIALES, 13, "¿A qué continente pertenece Tailandia?"),
                new Question(SOCIALES, 14, "¿A qué continente pertenece Kenia?"),
                new Question(SOCIALES, 15, "¿A qué continente pertenece Suecia?"),
                new Question(SOCIALES, 16, "¿A qué continente pertenece Guatemala?"),
                new Question(SOCIALES, 17, "¿Cuál es el continente más grande del mundo?"),
                new Question(SOCIALES, 18, "¿Qué nombre reciben las aguas subterráneas?"),
                new Question(SOCIALES, 19, "¿En qué unidades se miden la latitud y la longitud de un punto?"),
                new Question(SOCIALES, 20, "¿Cuál es la región española más al sur?"),
                new Question(SOCIALES, 21, "¿Cuál es la capital de España?"),
                new Question(SOCIALES, 22, "¿Cuál es la capital de Francia?"),
                new Question(SOCIALES, 23, "¿Cuál es la capital de Alemania?"),
                new Question(SOCIALES, 24, "¿Cuál es la capital de Reino Unido?"),
                new Question(SOCIALES, 25, "¿Cuál es la capital de Australia?"),
                new Question(SOCIALES, 26, "¿Cuál es la capital de Noruega?"),
                new Question(SOCIALES, 27, "¿En qué año fue aprobada la Constitución española que tenemos actualmente?"),
                new Question(SOCIALES, 28, "¿Cuántas comunidades autónomas hay en España?"),
                new Question(SOCIALES, 29, "¿Cuántas ciudades autónomas hay en España?"),
                new Question(SOCIALES, 30, "¿Cuál es la comunidad autónoma más grande de España?"),
                new Question(SOCIALES, 31, "¿Cuál es la comunidad autónoma más poblada de España?"),
                new Question(SOCIALES, 32, "¿Cuáles son los tres tipos de poder político que hay en España? Legislativo, judicial y..."),
                new OptionQuestion(SOCIALES, 33, "¿Qué modelo de gobierno tiene España?",
                        Arrays.asList(new Option('a', "Monarquía absoluta"),
                                new Option('b', "República"),
                                new Option('c', "Monarquía parlamentaria"))),
                new Question(SOCIALES, 34, "¿Qué lengua oficial hay en las Illes Balears aparte del castellano?"),
                new Question(SOCIALES, 35, "¿Qué lengua oficial hay en el País Vasco aparte del castellano?"),
                new OptionQuestion(SOCIALES, 36, "¿Qué sector económico es el predominante en la economía de España?",
                        Arrays.asList(new Option('a', "Primario"),
                                new Option('b', "Secundario"),
                                new Option('c', "Terciario"))),
                new OptionQuestion(SOCIALES, 37, "¿En cuántas etapas se divide la historia según los expertos?",
                        Arrays.asList(new Option('a', "3"),
                                new Option('b', "5"),
                                new Option('c', "7"))),
                new Question(SOCIALES, 38, "¿Cómo se llaman los pueblos que no permanecían en sitios fijos y se trasladaban en busca de alimentos?"),
                new Question(SOCIALES, 39, "¿Cómo se llaman los pueblos que dejaron de ir de un sitio a otro y se quedaron fijos en un sitio?"),
                new Question(SOCIALES, 40, "¿Cómo llamaron los romanos a la península Ibérica?"),
                new Question(SOCIALES, 41, "¿Qué idioma hablaban los romanos?"),
                new OptionQuestion(SOCIALES, 42, "¿En qué siglo se deshizo el Imperio romano?",
                        Arrays.asList(new Option('a', "V d.C."),
                                new Option('b', "I a.C."),
                                new Option('c', "IV d.C."))),
                new Question(SOCIALES, 43, "¿Qué etapa histórica comienza con la aparición de la escritura?"),
                new Question(SOCIALES, 44, "¿Qué etapa histórica comienza con la caída del imperio romano?"),
                new Question(SOCIALES, 45, "¿Qué etapa histórica comienza tras el descubrimiento de América?"),
                new Question(SOCIALES, 46, "¿Qué etapa histórica comienza tras la Revolución Francesa?"),
                new OptionQuestion(SOCIALES, 47, "¿A quién se le atribuye la invención de la imprenta?",
                        Arrays.asList(new Option('a', "Leonardo da Vinci"),
                                new Option('b', "Johannes Guttenberg"),
                                new Option('c', "Thomas Edison"))),
                new OptionQuestion(SOCIALES, 48, "¿Cuál fue el invento que resultó esencial para el desarrollo de la Revolución Industrial?",
                        Arrays.asList(new Option('a', "Coche"),
                                new Option('b', "Rueda"),
                                new Option('c', "Máquina de vapor"))),
                new OptionQuestion(SOCIALES, 49, "¿A qué inventor se le atribuye la invención del teléfono?",
                        Arrays.asList(new Option('a', "Thomas Edison"),
                                new Option('b', "Alexander Graham Bell"),
                                new Option('c', "Nikola Tesla"))),
                new OptionQuestion(SOCIALES, 50, "¿Cuál fue el conflicto bélico más importante del siglo XX?",
                        Arrays.asList(new Option('a', "Primera Guerra Mundial"),
                                new Option('b', "Guerra de Corea"),
                                new Option('c', "Segunda Guerra Mundial"))),
                new OptionQuestion(CASTELLANO, 1, "¿Cuál es la palabra intrusa en esta familia?",
                        Arrays.asList(new Option('a', "Arena"),
                                new Option('b', "Área"),
                                new Option('c', "Arenal"))),
                new OptionQuestion(CASTELLANO, 2, "En la oración La vieja fábrica, ¿qué función realiza la?",
                        Arrays.asList(new Option('a', "Determinante"),
                                new Option('b', "Núcleo"),
                                new Option('c', "Complemento"))),
                new OptionQuestion(CASTELLANO, 3, "¿Cuál es el pretérito imperfecto de subjuntivo del verbo decir?",
                        Arrays.asList(new Option('a', "Dijera o dijese."),
                                new Option('b', "Dije"),
                                new Option('c', "Dijere"))),
                new OptionQuestion(CASTELLANO, 4, "¿Cuándo llevan tilde las palabras agudas?",
                        Arrays.asList(new Option('a', "Siempre"),
                                new Option('b', "Si terminan en vocal o en consonante n,s."),
                                new Option('c', "Si terminan en consonante diferente a n o s."))),
                new OptionQuestion(CASTELLANO, 5, "¿Cuál de estas palabras lleva tilde?",
                        Arrays.asList(new Option('a', "Cartera"),
                                new Option('b', "Parpado"),
                                new Option('c', "Tenedor"))),
                new Question(CASTELLANO, 6, "¿Cuál es el femenino de la palabra alcalde?"),
                new ImageQuestion(CASTELLANO, 7, "¿Cómo se llama la persona que toca este instrumento?", R.drawable.violin),
                new OptionQuestion(CASTELLANO, 8, "¿Cuál de estos sustantivos es propio?",
                        Arrays.asList(new Option('a', "Rebaño"),
                                new Option('b', "Árbol"),
                                new Option('c', "Andrés"))),
                new ImageQuestion(CASTELLANO, 9, "¿Quién es?", R.drawable.cervantes),
                new OptionQuestion(CASTELLANO, 10, "¿Qué palabra lleva hache?",
                        Arrays.asList(new Option('a', "Invierno"),
                                new Option('b', "Orario"))),
                new OptionQuestion(CASTELLANO, 11, "¿Por qué el enunciado Rebajas de invierno no es una oración?",
                        Arrays.asList(new Option('a', "No tiene sujeto."),
                                new Option('b', "No consta de sujeto y predicado y no posee un verbo en forma personal."))),
                new OptionQuestion(CASTELLANO, 12, "¿Cuál de estos grupos son sinónimos entre ellos?",
                        Arrays.asList(new Option('a', "Limpiar, lavar, asear."),
                                new Option('b', "Andar, caminar, contemplar."))),
                new Question(CASTELLANO, 13, "¿Cuál es el antónimo de coser?"),
                new OptionQuestion(CASTELLANO, 14, "¿Cuál empieza por Y?",
                        Arrays.asList(new Option('a', "Llugular/Yugular."),
                                new Option('b', "Lluvia/Yuvia"))),
                new Question(CASTELLANO, 15, "¿Qué letra le falta a jerse...?"),
                new Question(CASTELLANO, 16, "¿Cuál es el prefijo de superdotado?"),
                new Question(CASTELLANO, 17, "¿Cuál es el prefijo de antigripal?"),
                new OptionQuestion(CASTELLANO, 18, "Completa la oración, Este utensilio sirve para ... el pan.",
                        Arrays.asList(new Option('a', "Rallar con ll."),
                                new Option('b', "Rayar con y"))),
                new OptionQuestion(CASTELLANO, 19, "¿Cuál es la palabra correcta? Los jueces ... al acusado porque era inocente.",
                        Arrays.asList(new Option('a', "Absolvieron"),
                                new Option('b', "Absorbieron"))),
                new OptionQuestion(CASTELLANO, 20, "¿Cuál de estas afirmaciones es falsa?",
                        Arrays.asList(new Option('a', "Las palabras monosílabas jamás se acentúan."),
                                new Option('b', "Más lleva tilde cuando significa cantidad."))),
                new OptionQuestion(CASTELLANO, 21, "La palabra UNICEF es",
                        Arrays.asList(new Option('a', "Una abreviatura"),
                                new Option('b', "Siglas"))),
                new OptionQuestion(CASTELLANO, 22, "La palabra Dña es",
                        Arrays.asList(new Option('a', "Una abreviatura"),
                                new Option('b', "Siglas"))),
                new OptionQuestion(CASTELLANO, 23, "¿Cuál es la palabra castellana correspondiente al extranjerismo confort?",
                        Arrays.asList(new Option('a', "Comodidad"),
                                new Option('b', "Encanto"))),
                new OptionQuestion(CASTELLANO, 24, "¿Cuál es la palabra castellana correspondiente al extranjerismo grill?",
                        Arrays.asList(new Option('a', "Hamburguesa"),
                                new Option('b', "Parrilla"))),
                new OptionQuestion(CASTELLANO, 25, "Las preposiciones son",
                        Arrays.asList(new Option('a', "Enlaces que unen dos palabras o grupos de palabras que corresponden a ideas semejantes"),
                                new Option('b', "Enlaces que unen dos palabras de modo que la segunda complementa a la primera"))),
                new OptionQuestion(CASTELLANO, 26, "Las conjunciones son",
                        Arrays.asList(new Option('a', "Enlaces que unen dos palabras o grupos de palabras que corresponden a ideas semejantes"),
                                new Option('b', "Enlaces que unen dos palabras de modo que la segunda complementa a la primera"))),
                new OptionQuestion(CASTELLANO, 27, "El eufemismo de muerte es",
                        Arrays.asList(new Option('a', "Sustracción"),
                                new Option('b', "Defunción"))),
                new OptionQuestion(CASTELLANO, 28, "Completa la palabra a...edrez.",
                        Arrays.asList(new Option('a', "J"),
                                new Option('b', "G"))),
                new OptionQuestion(CASTELLANO, 29, "Completa la palabra e...emplo",
                        Arrays.asList(new Option('a', "J"),
                                new Option('b', "G"))),
                new OptionQuestion(CASTELLANO, 30, "Completa la palabra ...eranio",
                        Arrays.asList(new Option('a', "J"),
                                new Option('b', "G"))),
                new OptionQuestion(CASTELLANO, 31, "Completa la palabra e...pléndido",
                        Arrays.asList(new Option('a', "X"),
                                new Option('b', "S"))),
                new OptionQuestion(CASTELLANO, 32, "Completa la palabra e...plícito",
                        Arrays.asList(new Option('a', "X"),
                                new Option('b', "S"))),
                new OptionQuestion(CASTELLANO, 33, "Completa la palabra e...quema",
                        Arrays.asList(new Option('a', "X"),
                                new Option('b', "S"))),
                new Question(CASTELLANO, 34, "¿Cuáles son las siglas del Documento Nacional de Identidad?"),
                new OptionQuestion(CASTELLANO, 35, "La oración Martín es una joya tiene",
                        Arrays.asList(new Option('a', "Sentido literal"),
                                new Option('b', "Sentido figurado"))),
                new OptionQuestion(CASTELLANO, 36, "La oración Eva es una lapa, no te la quitas de encima tiene",
                        Arrays.asList(new Option('a', "Sentido literal"),
                                new Option('b', "Sentido figurado"))),
                new OptionQuestion(CASTELLANO, 37, "La oración Entro en el gallinero a recoger los huevos tiene",
                        Arrays.asList(new Option('a', "Sentido literal"),
                                new Option('b', "Sentido figurado"))),
                new OptionQuestion(CASTELLANO, 38, "En Alicia escribió un cuento precioso. Un cuento precioso es",
                        Arrays.asList(new Option('a', "Complemento indirecto CI"),
                                new Option('b', "Complemento directo CD"))),
                new OptionQuestion(CASTELLANO, 39, "En Vino ayer su primo Juan. Ayer es",
                        Arrays.asList(new Option('a', "Complemento circunstancial de modo"),
                                new Option('b', "Complemento circunstancial de tiempo"))),
                new OptionQuestion(CASTELLANO, 40, "Algo que no es legal es",
                        Arrays.asList(new Option('a', "Contralegal"),
                                new Option('b', "Ilegal"),
                                new Option('c', "Antilegal")))
                new OptionQuestion(MATEMATICAS, 1, "Escribe el valor de CMLXII.",
                        Arrays.asList(new Option('a', "926"),
                                new Option('b', "962"),
                                new Option('c', "1962"))),
                new OptionQuestion(MATEMATICAS, 2, "Escribe el valor de MMDCCVI",
                        Arrays.asList(new Option('a', "2706"),
                                new Option('b', "2506"),
                                new Option('c', "2556"))),
                new OptionQuestion(MATEMATICAS, 3, "Escribe el valor de CMXLII.",
                        Arrays.asList(new Option('a', "942"),
                                new Option('b', "922"),
                                new Option('c', "1952"))),
                new OptionQuestion(MATEMATICAS, 4, "Escribe en números romanos 1987.",
                        Arrays.asList(new Option('a', "MMLXXXVII"),
                                new Option('b', "MCMLXXXVII"),
                                new Option('c', "MCMLXXVII"))),
                new OptionQuestion(MATEMATICAS, 5, "Escribe en números romanos 1439.",
                        Arrays.asList(new Option('a', "CXXXIX"),
                                new Option('b', "MCDXXXIX"),
                                new Option('c', "CDXXXIX"))),
                new OptionQuestion(MATEMATICAS, 6, "Escribe en números romanos 1814.",
                        Arrays.asList(new Option('a', "CXXXIX"),
                                new Option('b', "CCDXXIX"),
                                new Option('c', "MDCCCXIV"))),
                new OptionQuestion(MATEMATICAS, 7, "En una cafetería recibieron ayer un pedido de 9 packs de refrescos con 24 refrescos cada uno. Por la mañana han servido 15. ¿Cuántos refrescos les quedan?",
                        Arrays.asList(new Option('a', "201"),
                                new Option('b', "136"),
                                new Option('c', "13"))),
                new OptionQuestion(MATEMATICAS, 8, "Mario ha anotado en un partido de baloncesto 8 triples y 26 canastas. ¿Cuántos puntos ha anotado Mario?",
                        Arrays.asList(new Option('a', "76"),
                                new Option('b', "35"),
                                new Option('c', "70"))),
                new OptionQuestion(MATEMATICAS, 9, "A una gruta han llegado 16 coches con 5 personas en cada uno y otras 150 personas en autobuses. ¿Cuántos visitantes han llegado en autobuses más que en coches?",
                        Arrays.asList(new Option('a', "15"),
                                new Option('b', "70"),
                                new Option('c', "20"))),
                new OptionQuestion(MATEMATICAS, 10, "Gustavo compra 16 botes de zumo a 2 € cada uno. Paga y le devuelven 3 €. ¿Cuánto dinero ha entregado para pagar?.",
                        Arrays.asList(new Option('a', "32"),
                                new Option('b', "35"),
                                new Option('c', "29"))),
                new OptionQuestion(MATEMATICAS, 11, "Para la clase de Plástica, Olga ha comprado 4 cajas con 12 ceras cada una y 2 cajas con 24 ceras cada una. ¿Cuántas ceras ha comprado en total?",
                        Arrays.asList(new Option('a', "56"),
                                new Option('b', "14"),
                                new Option('c', "16"))),
                new OptionQuestion(MATEMATICAS, 12, "Carla ha comprado 4 libros de una colección. Cada libro cuesta 14 € y ha entregado para pagar 70 €. ¿Cuánto dinero le devuelven?",
                        Arrays.asList(new Option('a', "56"),
                                new Option('b', "14"),
                                new Option('c', "16"))),
                new OptionQuestion(MATEMATICAS, 13, "Un frutero vendió 15 cajas de naranjas de 25 kilos cada una por un total de 1.125 €. ¿Cuánto costaba cada kilo de naranjas?",
                        Arrays.asList(new Option('a', "3"),
                                new Option('b', "6"),
                                new Option('c', "2"))),
                new OptionQuestion(MATEMATICAS, 14, "Un cine llenó sus 250 butacas en todas las sesiones. En total asistieron 403 niños y 347 adultos. Cuántas sesiones hubo en el cine?",
                        Arrays.asList(new Option('a', "96"),
                                new Option('b', "36"),
                                new Option('c', "126"))),
        new OptionQuestion(MATEMATICAS, 15, "Un grupo de 14 amigos ha ido a cenar. Han pagado 254 € por las pizzas y 96 € por los refrescos. El total lo han pagado a partes iguales. ¿Cuánto ha tenido que poner cada uno?",
                Arrays.asList(new Option('a', "1400"),
                        new Option('b', "900"),
                        new Option('c', "1260"))),
                new OptionQuestion(MATEMATICAS, 16, "Maite se ha comprado un coche por 14.600 €. Primero pagó 2.000 € y el resto lo pagará en 14 mensualidades iguales. ¿Cuánto paga en cada mensualidad?",
                        Arrays.asList(new Option('a', "25"),
                                new Option('b', "20"),
                                new Option('c', "15"))),
                new OptionQuestion(MATEMATICAS, 17, "En un vivero pagaron 900 € por 18 cajas con 25 plantas cada una. Después, vendieron cada planta a 3 €. ¿Cuánto ganaron en la venta de cada planta?",
                        Arrays.asList(new Option('a', "2"),
                                new Option('b', "3"),
                                new Option('c', "1"))),
                new OptionQuestion(MATEMATICAS, 18, "Un grupo de 312 personas quiere cruzar un lago. Un tercio cruzará en un barco y el resto, en barcas de 13 plazas. ¿Cuántas barcas de 13 plazas utilizarán?",
                        Arrays.asList(new Option('a', "16"),
                                new Option('b', "14"),
                                new Option('c', "18"))),
                new OptionQuestion(MATEMATICAS, 19, "Un circuito para bicicletas mide 15 km. Cristina ha recorrido un quinto del circuito y su prima Eva, dos tercios. ¿Quién ha recorrido más kilómetros?",
                        Arrays.asList(new Option('a', "Eva"),
                                new Option('b', "Cristina"),
                                               new OptionQuestion(MATEMATICAS, 20, "Alejandro tenía en su hucha 60 €. Se gastó un cuarto del dinero en un libro y un quinto en una camiseta. ¿Cuánto dinero le quedó?",
                        Arrays.asList(new Option('a', "33"),
                                new Option('b', "27"),
                                new Option('c', "23"))),
                                new OptionQuestion(MATEMATICAS, 21, "La capacidad del biberón de Natalia es de 25 centilitros. Natalia toma cada día un biberón completo y tres quintas partes de otro. ¿Cuántos centilitros de leche toma Natalia al día?",
                                        Arrays.asList(new Option('a', "30"),
                                                new Option('b', "45"),
                                                new Option('c', "40"))),
                                                             new OptionQuestion(MATEMATICAS, 22, "Un camión y su carga pesan 5.000 kg. El camión pesa dos octavos del peso total. ¿Cuántos kilos pesa la carga?",
                                        Arrays.asList(new Option('a', "2150"),
                                                new Option('b', "3750"),
                                                new Option('c', "1520"))),
                                new OptionQuestion(MATEMATICAS, 23, "Las edades de los tres hermanos de Aurora son tres números de una cifra consecutivos. Su producto es 210. ¿Qué edades son?",
                                        Arrays.asList(new Option('a', " 5,6,7"),
                                                new Option('b', "4,5,6"),
                                                new Option('c', "7,8,9"))),
                                new OptionQuestion(MATEMATICAS, 24, "Tres amigos han corrido en una carrera de 20 corredores. Sus tres dorsales eran números de dos cifras consecutivos y su producto era 2.730. " +
                                        "¡Qué números llevaban los tres amigos en sus dorsales?",
                                        Arrays.asList(new Option('a', "13,14,15"),
                                                new Option('b', "10,11,12"),
                                                new Option('c', "16,17,18"))),
                                new OptionQuestion(MATEMATICAS, 25, "Juan ha comprado en rebajas 9 juegos de ordenador por 261 €. Cada juego por separado costaba 30 €. Cuánto se ha ahorrado Juan en total?",
                                        Arrays.asList(new Option('a', "9"),
                                                new Option('b', "1"),
                                                new Option('c', "5"))),
                                new OptionQuestion(MATEMATICAS, 26, "Una empresa está poniendo la instalación eléctrica a un bloque de 12 pisos. En cada piso emplean 137 metros de cable y llevan una bobina con 1.700 metros. ¿Cuántos metros de cable les sobran?",
                                        Arrays.asList(new Option('a', "65"),
                                                new Option('b', "55"),
                                                new Option('c', "56"))),
                                new OptionQuestion(MATEMATICAS, 27, "La longitud de una pista de atletismo es de 400 m. ¿Cuántas vueltas completas se dan en una carrera de 10 km?",
                                        Arrays.asList(new Option('a', "7"),
                                                new Option('b', "6"),
                                                new Option('c', "5"))),
                                new OptionQuestion(MATEMATICAS, 28, "El año pasado Lorena medía 1,58 m y este año mide 1,65 m. ¿Cuántos centímetros ha crecido Lorena?",
                                        Arrays.asList(new Option('a', "65"),
                                                new Option('b', "55"),
                                                new Option('c', "56"))),
                                new OptionQuestion(MATEMATICAS, 29, "La profesora de Plástica ha cortado una cinta en 12 trozos de 10,5 cm cada uno. ¿Cuánto medía la cinta?",
                                        Arrays.asList(new Option('a', " 1 m 26 cm"),
                                                new Option('b', "1 m 16 cm"),
                                                new Option('c', "2 m 6 cm"))),
                                new OptionQuestion(MATEMATICAS, 30, "La profesora de Plástica ha cortado una cinta en 12 trozos de 10,5 cm cada uno. ¿Cuánto medía la cinta?",
                                        Arrays.asList(new Option('a', "  64"),
                                                new Option('b', "45"),
                                                new Option('c', "54"))),
                                new OptionQuestion(MATEMATICAS, 31, "Lola cocinó 15 bandejas de cruasanes. En cada una había 28 cruasanes. Después, los envasó en bolsas de 3 cruasanes y vendió cada bolsa a 6 €. ¿Cuánto dinero obtuvo?",
                                        Arrays.asList(new Option('a', "489"),
                                                new Option('b', "840"),
                                                new Option('c', "880"))),
                                new OptionQuestion(MATEMATICAS, 32, "En una tienda compraron 25 neveras por 9.375 €. El mes siguiente, vendieron 18 neveras. Cada una la vendieron 40 € más cara de lo que les costó. ¿Cuánto dinero obtuvieron?",
                                        Arrays.asList(new Option('a', "7470"),
                                                new Option('b', "7740"),
                                                new Option('c', "7704"))),
                                new OptionQuestion(MATEMATICAS, 33, "En la frutería de Teresa, un kilo de pimientos cuesta 2,35 € y un kilo de zanahorias, 1,05 €. Marina ha comprado 2 kilos de pimientos y 1 kilo de zanahorias. ¿Cuánto pagará en total?",
                                        Arrays.asList(new Option('a', " 6 coma 2"),
                                                new Option('b', "8 coma 6"),
                                                new Option('c', "8 coma 2"))),
                                new OptionQuestion(MATEMATICAS, 34, "El coche de Gustavo gasta 0,075 litros de gasolina por cada kilómetro recorrido. Esta semana Gustavo ha hecho un viaje de 125 km, otro viaje de 264 km y otro de 59 km. ¿Cuántos litros de gasolina ha gastado?",
                                        Arrays.asList(new Option('a', "38 coma 025"),
                                                new Option('b', "35 coma 85"),
                                                new Option('c', "35 coma 85"))),
                                new OptionQuestion(MATEMATICAS, 35, "Milagros tenía 15,78 €. Compró dos libros que costaron 9,75 € y 4,99 €, respectivamente. ¿Cuánto dinero le quedó? ",
                                        Arrays.asList(new Option('a', "1 coma 4"),
                                                new Option('b', " 1 coma 04"),
                                                new Option('c', "1 coma 44."))),
                                new OptionQuestion(MATEMATICAS, 36, "Paloma compró 100 gomas de borrar para venderlas en su papelería. Pagó por ellas 38 €. Después, vendió cada goma a 0,95 €. Cuánto dinero ganó por la venta de todas las gomas?",
                                        Arrays.asList(new Option('a', "0 coma 57"),
                                                new Option('b', " 0 coma 75"),
                                                new Option('c', "0 coma 95"))),
                                new OptionQuestion(MATEMATICAS, 37, "En una oficina han hecho hoy 120 llamadas de teléfono. Tres quintos han sido llamadas locales, 15 llamadas han sido nacionales y el resto, internacionales. Qué tipo de llamadas es el que más han hecho?",
                                        Arrays.asList(new Option('a', "Locales"),
                                                new Option('b', "Nacionales"),
                                                new Option('c', "Internacionales"))),
                                new OptionQuestion(MATEMATICAS, 38, "Un saltamontes dio tres saltos consecutivos. En el primero saltó 0,25 m y en cada uno de los siguientes saltó 0,09 cm más que en el anterior. Qué longitud saltó en total?",
                                        Arrays.asList(new Option('a', "2 coma 64"),
                                                new Option('b', "32 coma 25"),
                                                new Option('c', " 2 coma 09"))),
        );
    }

    /**
     * Devuelve una lista de preguntas con el tamaño indicado y sobre la temática indicada.
     *
     * @param limit   cantidad de preguntas
     * @param subject temática de las preguntas
     * @return lista de preguntas con el tamaño indicado y sobre la temática indicada
     */
    public static List<Question> randomQuestions(int limit, Subject subject) {
        if (limit >= subject.getSize()) throw new IllegalArgumentException();
        int[] randomNumbers = Utilities.randomNumbers(1, subject.getSize(), MainActivity.N_QUESTIONS);
        List<Question> questions = new ArrayList<>(limit);
        for (int number : randomNumbers) {
            Question question = getQuestionBy(number, subject);
            if (question != null && questions.size() < limit) questions.add(question);
        }
        return questions;
    }

    /**
     * Devuelve una lista de preguntas con el tamaño indicado
     *
     * @param limit cantidad de preguntas
     * @return lista de preguntas con el tamaño indicado
     */
    public static List<Question> randomQuestions(int limit) {
        List<Question> questions = new ArrayList<>(limit);
        int[] randomNumbers = Utilities.randomNumbers(0, questions.size() - 1, MainActivity.N_QUESTIONS);
        for (int number : randomNumbers) {
            Question question = QuestionUtils.questions.get(number);
            if (question != null) questions.add(question);
        }
        return questions;
    }

    /**
     * Devuelve la pregunta con el id y de la temática indicada
     *
     * @param id      identificador de la pregunta a buscar
     * @param subject temática de la pregunta a buscar
     * @return pregunta con el id y de la temática indicada o null si no existe
     */
    public static Question getQuestionBy(int id, Subject subject) {
        for (Question question : questions)
            if (question.getId() == id && question.getSubject().equals(subject)) return question;
        return null;
    }
}
